name: ${project.name}
main: org.jakub1221.herobrineai.HerobrineAI
version: ${project.version}
description: ${project.description}
commands:
    hb-ai:
      description: Main command.
      usage: /hb-ai help
    hb:
      description: Main command.
      usage: /hb help